In [1]:
import numpy as np

## Creating Array

In [16]:
#np.array
arr = np.array([1,2,3])
print(arr)
print('-------------------------')

#np.zeros
zeros = np.zeros((2,3))
print(zeros)
print('-------------------------')

#np.ones
ones = np.ones((2,3))
print(ones)


[1 2 3]
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
-------------------------
[[1. 1. 1.]
 [1. 1. 1.]]


## a = b  vs  a = b.copy()

In [17]:
# arr = zeros
arr = zeros
arr[0,1] = 5
print(arr)
print('-------------------------')
print(zeros)

[[0. 5. 0.]
 [0. 0. 0.]]
-------------------------
[[0. 5. 0.]
 [0. 0. 0.]]


In [18]:
# arr = zeros2.copy()

zeros2 = np.zeros((2,3))
arr = zeros2.copy()
arr[0][1] = 5 
print(arr)
print('-------------------------')
print(zeros2)

[[0. 5. 0.]
 [0. 0. 0.]]
-------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


## Random int and Reshape()

In [19]:
arr = np.random.randint(0 , 1000 , 40)
arr = arr.reshape(4,10)
print(arr)

[[189  92 632 734 762 376 349 802 784 378]
 [337 694 679 770 924 552 688 883 644 325]
 [243 166 594 435  91 165 804 987 161 128]
 [441 405  62  64  33 388 667 678 740 635]]


## Slicing

In [20]:
# [Start : End : Step]
#arr[ 0:4:2 , 0:10:3 ]

# [Start(0) : End-1(end) : Step(1)]
#print(arr[0,1]) #element
#print(arr[2,:]) #row
#print(arr[:,-2]) #columns
print(arr[0:2,2:arr.shape[1]]) #random slice

[[632 734 762 376 349 802 784 378]
 [679 770 924 552 688 883 644 325]]


In [21]:
# default start = 0 end = len(arr) step = 1
arr[:, 2:5]

array([[632, 734, 762],
       [679, 770, 924],
       [594, 435,  91],
       [ 62,  64,  33]])

## Operations On Array

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([3,4,5])

# Add +
print(arr1 + arr2)

print('-------------------------')

# Subtract -
print(arr1 - arr2)

print('-------------------------')

# Multiply *
print(arr1 * arr2)

print('-------------------------')

# Division /
print(arr1 / arr2)

[4 6 8]
-------------------------
[-2 -2 -2]
-------------------------
[ 3  8 15]
-------------------------
[0.33333333 0.5        0.6       ]


## Dot Product

In [23]:
# To return transpose arr.T 

print(np.dot(arr1,arr1.T))
arr3 = arr1@arr2
arr3

14


26

## Broadcasting

In [24]:
arr3 = np.zeros(9).reshape(3,3)
vector = np.array([1,0,1])

#ADD VECTOR COLUMN-WISE
arr3+vector.reshape(-1,1) #arr3+vector for row-wise

array([[1., 1., 1.],
       [0., 0., 0.],
       [1., 1., 1.]])

## Vectoraization

In [25]:
x = np.random.randint(0,1000,100000)

In [26]:
%%timeit -n 100
summ = 0
for i in x :
    summ += i 



22.4 ms ± 444 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%%timeit -n 100
summ = np.sum(x)


61.1 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Statistics

In [28]:
# sum of array 
print(np.sum(arr1))

# max value in array
print(np.max(arr1))

# mean for all values in array
print(np.mean(arr1))

# standard deviation|
print(np.std(arr1))

6
3
2.0
0.816496580927726


In [29]:
np.sum(arr3,axis=1)

array([0., 0., 0.])